[package]
name = "arccrypt"
version = "0.1.0"
edition = "2021"
authors = ["314ShadePi", "S3llen3"]
readme = "README.md"
description = "A Blockchain in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
